name: flutter_app # 应用或包名称
description: A new Flutter application. # 应用或包的描述、简介

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1 # 应用或包的版本号
author: 师春雷 <1558053958@qq.com>
homepage: https://github.com/shichunlei/flutter_app

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies: # 应用或包依赖的其它包或插件
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  amap_base_location: ^0.4.0+1

  # https://github.com/aagarwal1012/Animated-Text-Kit
  animated_text_kit: ^1.3.1

  # AzListView，Flutter 城市列表，联系人列表，自定义Header，索引，悬停效果。
  azlistview: ^0.1.2

  badges: ^1.1.0

  # 扫描二维码
  barcode_scan: ^1.0.0

  # 图表
  charts_flutter: ^0.6.0

  chewie: ^0.9.7

  city_picker: ^0.1.3

  city_pickers: ^0.1.23

  clippy_flutter:
    git:
      url: https://github.com/figengungor/clippy_flutter

  contact_picker: ^0.0.2

  crypto: ^2.1.1+1

  # 设备信息
  device_info: ^0.4.0+2

  # 网络请求库
  dio: ^2.1.13

  # 英文单词库
  english_words: ^3.1.5

  fancy_bottom_navigation: ^0.3.2

  # 图标库地址：https://feathericons.com/
  feather_icons_flutter: ^4.7.4

  flute_music_player:
    git:
      url: https://github.com/iampawan/Flute-Music-Player

  # 颜色选择器
  flutter_colorpicker: ^0.2.6

  # 刷新加载控件
  flutter_easyrefresh: ^1.2.7

  flutter_html: ^0.10.4

  # 侧滑菜单
  flutter_inner_drawer: ^0.3.0

  flutter_jd_address_selector:
    git:
      url: https://github.com/shichunlei/flutter_jd_address_selector

  # 加载提示组件
  flutter_spinkit: ^2.1.0

  # 瀑布流
  flutter_staggered_grid_view: ^0.2.7

  # banner
  flutter_swiper: ^1.1.6

  flutter_webview_plugin: ^0.3.5

  fluttery_seekbar: ^0.0.1

  # 图标库中文地址：http://www.fontawesome.com.cn/
  font_awesome_flutter: ^8.5.0

  http: ^0.12.0+2

  image_cropper: ^1.0.2

  # 图片选择器
  image_picker: ^0.6.1+2

  # 保存图片
  image_picker_saver: ^0.3.0

  # 引导页
  intro_slider: ^1.2.0

  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2

  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7

  multi_image_picker: ^4.5.0+2

  package_info: ^0.4.0+6

  palette_generator: ^0.2.0

  path_provider: ^1.2.0

  # PhotoView
  photo_view: ^0.4.2

  # 数据管理层
  provider: ^3.0.0+1

  # flutter 生成二维码
  qr_flutter: ^2.1.0+55

  #
  rounded_letter: ^0.0.6

  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.1+1

  share: ^0.6.2+1

  # SP
  shared_preferences: ^0.5.3+4

  # 数据库
  sqflite: ^1.1.6+3

  # 时间线 https://github.com/furkantektas/timeline_list
  timeline_list: ^0.0.5

  # 透明占位图片
  transparent_image: ^0.1.0

  url_launcher: ^5.0.5

  # 视频播放器器
  video_player: ^0.10.1+6

dev_dependencies: # 开发环境依赖的工具包（而不是flutter应用本身依赖的包）
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter. flutter相关的配置选项
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class. https://material.io/tools/icons/?icon=sd_storage&style=baseline
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/weather_backgrounds/
    - images/qdaily/
    - images/reader/
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/custom/iconfont.ttf

    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-Regular.ttf
        - asset: assets/fonts/Aleo-Italic.ttf
          style: italic
        - asset: assets/fonts/Aleo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Aleo-Light.ttf
          weight: 300

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
